


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.usuarios (user_id, nome_completo)
  values (
    new.id,
    new.raw_user_meta_data->>'name'
  );

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."update_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."crise_enxaqueca" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint,
    "inicio_crise" timestamp with time zone,
    "fim_crise" timestamp with time zone,
    CONSTRAINT "crise_datas_validas" CHECK ((("fim_crise" IS NULL) OR ("fim_crise" >= "inicio_crise")))
);


ALTER TABLE "public"."crise_enxaqueca" OWNER TO "postgres";


ALTER TABLE "public"."crise_enxaqueca" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."crise_enxaqueca_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fatores_desencadeantes" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL
);


ALTER TABLE "public"."fatores_desencadeantes" OWNER TO "postgres";


ALTER TABLE "public"."fatores_desencadeantes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fatores_desencadeantes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fatores_desencadeantes_registro_crise" (
    "registro_crise_id" bigint NOT NULL,
    "fatores_desencadeantes_id" bigint NOT NULL
);


ALTER TABLE "public"."fatores_desencadeantes_registro_crise" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."medicamentos" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL
);


ALTER TABLE "public"."medicamentos" OWNER TO "postgres";


ALTER TABLE "public"."medicamentos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."medicamentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."medicamentos_registro_crise" (
    "registro_crise_id" bigint NOT NULL,
    "medicamentos_id" bigint NOT NULL
);


ALTER TABLE "public"."medicamentos_registro_crise" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."opcoes_pergunta" (
    "id" bigint NOT NULL,
    "pergunta_id" bigint NOT NULL,
    "texto" "text" NOT NULL
);


ALTER TABLE "public"."opcoes_pergunta" OWNER TO "postgres";


ALTER TABLE "public"."opcoes_pergunta" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."opcoes_pergunta_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."perguntas_setup" (
    "id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "tipo" "text" NOT NULL,
    "passo_setup" integer NOT NULL,
    CONSTRAINT "perguntas_setup_tipo_check" CHECK (("tipo" = ANY (ARRAY['single_choice'::"text", 'multi_choice'::"text", 'range'::"text", 'text'::"text", 'boolean'::"text"])))
);


ALTER TABLE "public"."perguntas_setup" OWNER TO "postgres";


ALTER TABLE "public"."perguntas_setup" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."perguntas_setup_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sensacao_dor" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL
);


ALTER TABLE "public"."sensacao_dor" OWNER TO "postgres";


ALTER TABLE "public"."sensacao_dor" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."qualidade_dor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."registro_crise" (
    "id" bigint NOT NULL,
    "crise_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "intensidade_dor" bigint,
    "regiao_dor" "text",
    "lado" "text",
    "nivel_incapacidade" "text",
    "resumo" "text"
);


ALTER TABLE "public"."registro_crise" OWNER TO "postgres";


ALTER TABLE "public"."registro_crise" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."registro_crise_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."registro_diario" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "horas_sono" numeric(4,1),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "relato" "text",
    "ml_agua" integer,
    "humor" "text",
    "user_id" bigint,
    CONSTRAINT "registro_diario_humor_check" CHECK (("humor" = ANY (ARRAY['terrible'::"text", 'bad'::"text", 'so-so'::"text", 'okay'::"text", 'great'::"text"])))
);


ALTER TABLE "public"."registro_diario" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."registro_diario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."registro_diario_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."registro_diario_id_seq" OWNED BY "public"."registro_diario"."id";



CREATE TABLE IF NOT EXISTS "public"."respostas_setup" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "pergunta_id" bigint NOT NULL,
    "opcao_id" bigint,
    "valor_texto" "text",
    "valor_numero" numeric,
    "valor_acima_max" boolean DEFAULT false,
    "valor_booleano" boolean,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "valor_abaixo_min" boolean
);


ALTER TABLE "public"."respostas_setup" OWNER TO "postgres";


ALTER TABLE "public"."respostas_setup" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."respostas_setup_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sensacao_dor_registro_crise" (
    "registro_crise_id" bigint NOT NULL,
    "sensacao_dor_id" bigint NOT NULL
);


ALTER TABLE "public"."sensacao_dor_registro_crise" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sintoma_registro_crise" (
    "registro_crise_id" bigint NOT NULL,
    "sintoma_id" bigint NOT NULL
);


ALTER TABLE "public"."sintoma_registro_crise" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sintomas" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL
);


ALTER TABLE "public"."sintomas" OWNER TO "postgres";


ALTER TABLE "public"."sintomas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sintomas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "nome_completo" "text"
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


ALTER TABLE "public"."usuarios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usuarios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."view_respostas_setup" WITH ("security_invoker"='on') AS
 SELECT "rs"."id" AS "resposta_id",
    "rs"."user_id",
    "u"."nome_completo",
    "rs"."pergunta_id",
    "ps"."texto" AS "pergunta",
    "ps"."tipo" AS "tipo_pergunta",
    "ps"."passo_setup",
    "rs"."valor_numero",
    "rs"."valor_texto",
    "rs"."valor_booleano",
    "rs"."valor_acima_max",
    "op"."texto" AS "opcao_resposta",
    "rs"."created_at"
   FROM ((("public"."respostas_setup" "rs"
     JOIN "public"."perguntas_setup" "ps" ON (("ps"."id" = "rs"."pergunta_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "rs"."user_id")))
     LEFT JOIN "public"."opcoes_pergunta" "op" ON (("op"."id" = "rs"."opcao_id")));


ALTER VIEW "public"."view_respostas_setup" OWNER TO "postgres";


ALTER TABLE ONLY "public"."registro_diario" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."registro_diario_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."crise_enxaqueca"
    ADD CONSTRAINT "crise_enxaqueca_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fatores_desencadeantes"
    ADD CONSTRAINT "fatores_desencadeantes_nome_key" UNIQUE ("nome");



ALTER TABLE ONLY "public"."fatores_desencadeantes"
    ADD CONSTRAINT "fatores_desencadeantes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fatores_desencadeantes_registro_crise"
    ADD CONSTRAINT "fatores_desencadeantes_registro_crise_pkey" PRIMARY KEY ("registro_crise_id", "fatores_desencadeantes_id");



ALTER TABLE ONLY "public"."medicamentos"
    ADD CONSTRAINT "medicamentos_nome_key" UNIQUE ("nome");



ALTER TABLE ONLY "public"."medicamentos"
    ADD CONSTRAINT "medicamentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."medicamentos_registro_crise"
    ADD CONSTRAINT "medicamentos_registro_crise_pkey" PRIMARY KEY ("registro_crise_id", "medicamentos_id");



ALTER TABLE ONLY "public"."opcoes_pergunta"
    ADD CONSTRAINT "opcoes_pergunta_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."perguntas_setup"
    ADD CONSTRAINT "perguntas_setup_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sensacao_dor"
    ADD CONSTRAINT "qualidade_dor_nome_key" UNIQUE ("nome");



ALTER TABLE ONLY "public"."sensacao_dor"
    ADD CONSTRAINT "qualidade_dor_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registro_crise"
    ADD CONSTRAINT "registro_crise_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registro_diario"
    ADD CONSTRAINT "registro_diario_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."respostas_setup"
    ADD CONSTRAINT "respostas_setup_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sensacao_dor_registro_crise"
    ADD CONSTRAINT "sensacao_dor_registro_crise_pkey" PRIMARY KEY ("registro_crise_id", "sensacao_dor_id");



ALTER TABLE ONLY "public"."sintoma_registro_crise"
    ADD CONSTRAINT "sintoma_registro_crise_pkey" PRIMARY KEY ("registro_crise_id", "sintoma_id");



ALTER TABLE ONLY "public"."sintomas"
    ADD CONSTRAINT "sintomas_nome_key" UNIQUE ("nome");



ALTER TABLE ONLY "public"."sintomas"
    ADD CONSTRAINT "sintomas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_opcoes_pergunta" ON "public"."opcoes_pergunta" USING "btree" ("pergunta_id");



CREATE INDEX "idx_opcoes_pergunta_texto" ON "public"."opcoes_pergunta" USING "btree" ("texto");



CREATE INDEX "idx_respostas_pergunta" ON "public"."respostas_setup" USING "btree" ("pergunta_id");



CREATE INDEX "idx_respostas_user" ON "public"."respostas_setup" USING "btree" ("user_id");



CREATE OR REPLACE TRIGGER "trg_registro_diario_updated_at" BEFORE UPDATE ON "public"."registro_diario" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



ALTER TABLE ONLY "public"."crise_enxaqueca"
    ADD CONSTRAINT "crise_enxaqueca_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."fatores_desencadeantes_registro_crise"
    ADD CONSTRAINT "fatores_desencadeantes_registro__fatores_desencadeantes_id_fkey" FOREIGN KEY ("fatores_desencadeantes_id") REFERENCES "public"."fatores_desencadeantes"("id");



ALTER TABLE ONLY "public"."fatores_desencadeantes_registro_crise"
    ADD CONSTRAINT "fatores_desencadeantes_registro_crise_registro_crise_id_fkey" FOREIGN KEY ("registro_crise_id") REFERENCES "public"."registro_crise"("id");



ALTER TABLE ONLY "public"."medicamentos_registro_crise"
    ADD CONSTRAINT "medicamentos_registro_crise_medicamentos_id_fkey" FOREIGN KEY ("medicamentos_id") REFERENCES "public"."medicamentos"("id");



ALTER TABLE ONLY "public"."medicamentos_registro_crise"
    ADD CONSTRAINT "medicamentos_registro_crise_registro_crise_id_fkey" FOREIGN KEY ("registro_crise_id") REFERENCES "public"."registro_crise"("id");



ALTER TABLE ONLY "public"."opcoes_pergunta"
    ADD CONSTRAINT "opcoes_pergunta_pergunta_id_fkey" FOREIGN KEY ("pergunta_id") REFERENCES "public"."perguntas_setup"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."registro_crise"
    ADD CONSTRAINT "registro_crise_crise_id_fkey" FOREIGN KEY ("crise_id") REFERENCES "public"."crise_enxaqueca"("id");



ALTER TABLE ONLY "public"."registro_diario"
    ADD CONSTRAINT "registro_diario_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."respostas_setup"
    ADD CONSTRAINT "respostas_setup_opcao_id_fkey" FOREIGN KEY ("opcao_id") REFERENCES "public"."opcoes_pergunta"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."respostas_setup"
    ADD CONSTRAINT "respostas_setup_pergunta_id_fkey" FOREIGN KEY ("pergunta_id") REFERENCES "public"."perguntas_setup"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."respostas_setup"
    ADD CONSTRAINT "respostas_setup_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sensacao_dor_registro_crise"
    ADD CONSTRAINT "sensacao_dor_registro_crise_registro_crise_id_fkey" FOREIGN KEY ("registro_crise_id") REFERENCES "public"."registro_crise"("id");



ALTER TABLE ONLY "public"."sensacao_dor_registro_crise"
    ADD CONSTRAINT "sensacao_dor_registro_crise_sensacao_dor_id_fkey" FOREIGN KEY ("sensacao_dor_id") REFERENCES "public"."sensacao_dor"("id");



ALTER TABLE ONLY "public"."sintoma_registro_crise"
    ADD CONSTRAINT "sintoma_registro_crise_registro_crise_id_fkey" FOREIGN KEY ("registro_crise_id") REFERENCES "public"."registro_crise"("id");



ALTER TABLE ONLY "public"."sintoma_registro_crise"
    ADD CONSTRAINT "sintoma_registro_crise_sintoma_id_fkey" FOREIGN KEY ("sintoma_id") REFERENCES "public"."sintomas"("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Usuario acessa apenas suas respostas" ON "public"."respostas_setup" TO "authenticated" USING (("user_id" IN ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"())))) WITH CHECK (("user_id" IN ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



CREATE POLICY "Usuario pode atualizar seu proprio perfil" ON "public"."usuarios" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuario pode criar crises para si" ON "public"."crise_enxaqueca" FOR INSERT WITH CHECK (("user_id" IN ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



CREATE POLICY "Usuario pode criar seu proprio perfil" ON "public"."usuarios" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuario pode ver seu proprio perfil" ON "public"."usuarios" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuario pode ver suas crises" ON "public"."crise_enxaqueca" FOR SELECT USING (("user_id" IN ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



CREATE POLICY "Usuarios autenticados podem inserir medicamentos" ON "public"."medicamentos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Usuarios autenticados podem ler opcoes setup" ON "public"."opcoes_pergunta" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Usuarios autenticados podem ler perguntas setup" ON "public"."perguntas_setup" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Usuarios autenticados podem visualizar fatores desencadeantes" ON "public"."fatores_desencadeantes" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Usuarios autenticados podem visualizar medicamentos" ON "public"."medicamentos" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Usuarios autenticados podem visualizar sensacoes de dor" ON "public"."sensacao_dor" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Usuarios autenticados podem visualizar sintomas" ON "public"."sintomas" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."crise_enxaqueca" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fatores_desencadeantes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fatores_desencadeantes_registro_crise" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."medicamentos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."medicamentos_registro_crise" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."opcoes_pergunta" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."perguntas_setup" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."registro_crise" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."registro_diario" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."respostas_setup" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sensacao_dor" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sensacao_dor_registro_crise" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sintoma_registro_crise" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sintomas" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "usuario pode atualizar seus registros" ON "public"."registro_diario" FOR UPDATE USING (("user_id" = ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



CREATE POLICY "usuario pode inserir seus registros" ON "public"."registro_diario" FOR INSERT WITH CHECK (("user_id" = ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



CREATE POLICY "usuario pode ler seus registros" ON "public"."registro_diario" FOR SELECT USING (("user_id" = ( SELECT "usuarios"."id"
   FROM "public"."usuarios"
  WHERE ("usuarios"."user_id" = "auth"."uid"()))));



ALTER TABLE "public"."usuarios" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "usuarios_acessam_proprias_sensacoes" ON "public"."sensacao_dor_registro_crise" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "sensacao_dor_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "sensacao_dor_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"())))));



CREATE POLICY "usuarios_acessam_proprios_fatores" ON "public"."fatores_desencadeantes_registro_crise" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "fatores_desencadeantes_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "fatores_desencadeantes_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"())))));



CREATE POLICY "usuarios_acessam_proprios_medicamentos" ON "public"."medicamentos_registro_crise" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "medicamentos_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "medicamentos_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"())))));



CREATE POLICY "usuarios_acessam_proprios_registros" ON "public"."registro_crise" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."crise_enxaqueca" "ce"
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("ce"."id" = "registro_crise"."crise_id") AND ("u"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."crise_enxaqueca" "ce"
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("ce"."id" = "registro_crise"."crise_id") AND ("u"."user_id" = "auth"."uid"())))));



CREATE POLICY "usuarios_acessam_proprios_sintomas" ON "public"."sintoma_registro_crise" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "sintoma_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (("public"."registro_crise" "rc"
     JOIN "public"."crise_enxaqueca" "ce" ON (("ce"."id" = "rc"."crise_id")))
     JOIN "public"."usuarios" "u" ON (("u"."id" = "ce"."user_id")))
  WHERE (("rc"."id" = "sintoma_registro_crise"."registro_crise_id") AND ("u"."user_id" = "auth"."uid"())))));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."crise_enxaqueca" TO "anon";
GRANT ALL ON TABLE "public"."crise_enxaqueca" TO "authenticated";
GRANT ALL ON TABLE "public"."crise_enxaqueca" TO "service_role";



GRANT ALL ON SEQUENCE "public"."crise_enxaqueca_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."crise_enxaqueca_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."crise_enxaqueca_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fatores_desencadeantes" TO "anon";
GRANT ALL ON TABLE "public"."fatores_desencadeantes" TO "authenticated";
GRANT ALL ON TABLE "public"."fatores_desencadeantes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fatores_desencadeantes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fatores_desencadeantes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fatores_desencadeantes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fatores_desencadeantes_registro_crise" TO "anon";
GRANT ALL ON TABLE "public"."fatores_desencadeantes_registro_crise" TO "authenticated";
GRANT ALL ON TABLE "public"."fatores_desencadeantes_registro_crise" TO "service_role";



GRANT ALL ON TABLE "public"."medicamentos" TO "anon";
GRANT ALL ON TABLE "public"."medicamentos" TO "authenticated";
GRANT ALL ON TABLE "public"."medicamentos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."medicamentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."medicamentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."medicamentos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."medicamentos_registro_crise" TO "anon";
GRANT ALL ON TABLE "public"."medicamentos_registro_crise" TO "authenticated";
GRANT ALL ON TABLE "public"."medicamentos_registro_crise" TO "service_role";



GRANT ALL ON TABLE "public"."opcoes_pergunta" TO "anon";
GRANT ALL ON TABLE "public"."opcoes_pergunta" TO "authenticated";
GRANT ALL ON TABLE "public"."opcoes_pergunta" TO "service_role";



GRANT ALL ON SEQUENCE "public"."opcoes_pergunta_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."opcoes_pergunta_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."opcoes_pergunta_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."perguntas_setup" TO "anon";
GRANT ALL ON TABLE "public"."perguntas_setup" TO "authenticated";
GRANT ALL ON TABLE "public"."perguntas_setup" TO "service_role";



GRANT ALL ON SEQUENCE "public"."perguntas_setup_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."perguntas_setup_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."perguntas_setup_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sensacao_dor" TO "anon";
GRANT ALL ON TABLE "public"."sensacao_dor" TO "authenticated";
GRANT ALL ON TABLE "public"."sensacao_dor" TO "service_role";



GRANT ALL ON SEQUENCE "public"."qualidade_dor_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."qualidade_dor_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."qualidade_dor_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."registro_crise" TO "anon";
GRANT ALL ON TABLE "public"."registro_crise" TO "authenticated";
GRANT ALL ON TABLE "public"."registro_crise" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registro_crise_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registro_crise_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registro_crise_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."registro_diario" TO "anon";
GRANT ALL ON TABLE "public"."registro_diario" TO "authenticated";
GRANT ALL ON TABLE "public"."registro_diario" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registro_diario_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registro_diario_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registro_diario_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."respostas_setup" TO "anon";
GRANT ALL ON TABLE "public"."respostas_setup" TO "authenticated";
GRANT ALL ON TABLE "public"."respostas_setup" TO "service_role";



GRANT ALL ON SEQUENCE "public"."respostas_setup_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."respostas_setup_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."respostas_setup_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sensacao_dor_registro_crise" TO "anon";
GRANT ALL ON TABLE "public"."sensacao_dor_registro_crise" TO "authenticated";
GRANT ALL ON TABLE "public"."sensacao_dor_registro_crise" TO "service_role";



GRANT ALL ON TABLE "public"."sintoma_registro_crise" TO "anon";
GRANT ALL ON TABLE "public"."sintoma_registro_crise" TO "authenticated";
GRANT ALL ON TABLE "public"."sintoma_registro_crise" TO "service_role";



GRANT ALL ON TABLE "public"."sintomas" TO "anon";
GRANT ALL ON TABLE "public"."sintomas" TO "authenticated";
GRANT ALL ON TABLE "public"."sintomas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sintomas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sintomas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sintomas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."view_respostas_setup" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







